// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function DownloadBatch(arg1) {
  return window['go']['main']['App']['DownloadBatch'](arg1);
}

export function DownloadDefault(arg1) {
  return window['go']['main']['App']['DownloadDefault'](arg1);
}

export function GetFileExistsPolicy() {
  return window['go']['main']['App']['GetFileExistsPolicy']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ResolveFileExists(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveFileExists'](arg1, arg2, arg3);
}

export function SelectBatchFile() {
  return window['go']['main']['App']['SelectBatchFile']();
}

export function SetFileExistsPolicy(arg1) {
  return window['go']['main']['App']['SetFileExistsPolicy'](arg1);
}
