// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {downloader} from '../models';

export function CancelDownload():Promise<string>;

export function DownloadBatch(arg1:downloader.BatchDownloadRequest):Promise<downloader.BatchDownloadResult>;

export function DownloadDefault(arg1:downloader.DownloadRequest):Promise<downloader.DownloadResult>;

export function GetFileExistsPolicy():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ResolveFileExists(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SelectBatchFile():Promise<string>;

export function SetFileExistsPolicy(arg1:string):Promise<void>;
