// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {downloader} from '../models';

export function DownloadBatch(arg1:downloader.BatchDownloadRequest):Promise<downloader.BatchDownloadResult>;

export function DownloadDefault(arg1:downloader.DownloadRequest):Promise<downloader.DownloadResult>;

export function Greet(arg1:string):Promise<string>;

export function SelectBatchFile():Promise<string>;
